from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login', views.Login, name='login'),
    url(r'^landing', views.LandingPage, name='landing-page'),
    url(r'^api/authenticate', views.ApiAuthenticate, name='authenticate'),
    url(r'^api/create-user', views.CreateUser, name='create-user'),
    url(r'^api/create/travel/agency', views.CreateTravelAgency, name='create/travel/agency'),
    url(r'^api/add/spot', views.AddSpot, name='add/spot'),
    url(r'^api/create-package', views.CreatePackage, name='create-package'),
    url(r'^api/add-to-itinerary-details', views.AddSpotToPackage, name='add-to-itinerary-details'),
    url(r'^api/book-package', views.BookPackage, name='book-package'),
    url(r'^api/get-best-tours', views.GetBestTours, name='get-best-tours'),
    url(r'^api/get-featured-spots', views.GetFeaturedSpots, name='get-featured-spots'),
    url(r'^api/get/tour/guide/package', views.GetTGPackage, name='get/tour/guide/package'),
    url(r'^api/confirm/by/tour/guide', views.ConfirmByTourGuide, name='api/confirm/by/tour/guide'),
    url(r'^add-new-package/', views.AddPackage, name='add-new-package'),
    url(r'^addpackageaccomodation.html', views.AddPackage, name='addpackageaccomodation.html'),
    url(r'^addpackagetransportation.html', views.AddPackage, name='addpackagetransportation.html'),
    url(r'^addpackageitinerary.html', views.AddPackage, name='addpackageitinerary.html'),
    url(r'^addpackageinclusion.html', views.AddPackage, name='addpackageinclusion.html'),
    url(r'^signin.html', views.SignIn, name='signin.html'),
    url(r'^signup.html', views.CreateTravelAgency, name='signup.html'),
    url(r'^api/get-booked-tours', views.GetBookedPackages, name='get-booked-tours'),
    url(r'^api/post-friends', views.PostFriends, name='post-friends'),
    url(r'^api/add-rating-to-tour-guide-and-package', views.AddRatingToTourGuideAndPackage, name='add-rating-to-tour-guide-and-package'),
    url(r'^api/get-friends-activity', views.GetFriendsActivity, name='get-friends-activity'),
    url(r'^api/get/image', views.GetImage, name='get/image'),
    url(r'^api/create-custom-package', views.CreateCustomPackage, name='create-custom-package'),
    url(r'^api/get-custom-package-tours', views.GetMyCustomPackageTransactions, name='get-custom-package-tours'),
    url(r'^api/get-custom-packages', views.GetCustomPackages, name='get-custom-packages'),
    url(r'^api/get-all-package', views.GetAllPackage, name='get-all-package'),
    url(r'^api/edit-package', views.EditCustomPackage, name='edit-package'),
    url(r'^api/delete-spot-package', views.DeleteSpot, name='delete-spot-package'),
    url(r'^api/get/package/number/of/friends', views.RecommendPackageNumFriends, name='get/package/number/of/friends'),
    url(r'^api/cancel/booked/transaction', views.CancelBookedTransaction, name='cancel/booked/transaction'),
    url(r'^api/cancel/guide/transaction', views.CancelTourGuide, name='cancel/guide/transaction'),
    url(r'^api/comment/to/transaction', views.AddCommentToTransaction, name='comment/to/transaction'),
    url(r'^api/add/qr/code', views.AddQRCode, name='add/qr/code'),
    url(r'^api/use/qr/code', views.UseQRCode, name='user/qr/code'),
    url(r'^api/end/tour', views.EndTour, name='end/tour'),
    url(r'^api/start/tour', views.StartTour, name='end/tour'),
    url(r'^api/get/agency/package', views.GetAgencyPackage, name='get/agency/package'),
    url(r'^api/get/agency/transactions', views.GetAgencyTransaction, name='api/get/agency/transactions'),
    url(r'^api/get/all/spots', views.GetAllSpots, name='get/all/spots'),
    url(r'^api/post/firebase/token', views.FirebaseInstance, name='post/firebase/token'),
    url(r'^api/pili', views.ChooseTourGuide, name='pili'),
    url(r'^api/update/package', views.UpdatePackage, name='api/update/package'),
    url(r'^api/update/spots/package', views.UpdateSpotsPackage, name='api/update/package/spot'),
    url(r'^api/confirm/agency', views.AcceptTravelRequest, name='api/confirm/agency'),
    url(r'^api/delete/package', views.DeletePackage, name='api/delete/package')
]